### PR TITLE
Translate dataset

### LINKED ISSUE #6: Translate dataset to English
The main language of the project is English: works well mixed in programming languages like Python and provides a low barrier for non-Brazilian contributors. Today, the dataset we make available by default for them is a set of XMLs from [The Chamber of Deputies](http://www2.camara.leg.br/english), in Portuguese. We need attribute names and categorical values to be translated to English.

### PR DESCRIPTION
**Pull request by Irio**
Closes #6.

### CODE REVIEW

**Comment by cuducos** [comment]
Great PR, @irio!

**Comment by Irio** [comment]
Wasn't being able to convert the larger file - `AnosAnteriores.xml`, of 3GB - to CSV with my machine, with 16GB of RAM. Started an Amazon instance with 60GB of RAM and did it in a few minutes. 👯 

Here are the file size differences between government provided and generated CSVs:
```
-rw-r--r--@ 1 irio  staff    74M Aug  8 12:57 2016-08-08-AnoAnterior.csv
-rw-r--r--@ 1 irio  staff    37M Aug  8 12:57 2016-08-08-AnoAtual.csv
-rw-r--r--@ 1 irio  staff   291M Aug  8 13:01 2016-08-08-AnosAnteriores.csv
-rw-r--r--  1 irio  staff   674M Jul 25 21:30 AnoAnterior.xml
-rw-r--r--  1 irio  staff   317M Jul 25 21:00 AnoAtual.xml
-rw-r--r--  1 irio  staff   2.6G Jul 25 21:33 AnosAnteriores.xml
```

**Comment by Irio** [comment]
@cuducos Would love to have as much feedback from you as possible on this last commit, https://github.com/datasciencebr/serenata-de-amor/pull/7/commits/2460341aa0c420212559c27333488931b23421d4. Generally (e.g. didn't know the word "glosa" from "vlrGlosa") but also specifically on the translation of congress(man) and parliamentar(y), which I used interchangeably.

**Comment by cuducos** [comment]
I'm looking at this later this week. I can try to optimize the Python script to be able to run in “normal” computers too. Is that a priority?

**Comment by cuducos** [comment]
Some quick translation suggestions:

**Nome do dado**

* `txNomeParlamentar`, `ideCadastro` and `nuCarteiraParlamentar` should be `congressperson_name`, `congressperson_id` and `congressperson_document` (as _congressmen_ is gendered)
* `sgUF` could be `state` (usual in American English), `federative_unit` (more formal/literal) or `fu` (`uf` makes no sense in English)
* `txtCNPJCPF ` could be `ein` (Employer Identification Number, unique ID for tax payers in American English)
* If I got it right `txtNumero` could then be `ein_number`
* `txtTrecho` could be `leg_of_the_trip` (more used than _stretch_)

** subquota_description**

* `Publication subscriptions`
* `Consultancy, research and technical work` (typo, missing _h_ in _technical_)
* `Publicity of parliamentary activity`
* `Flight ticket issue`
* `Congressperson meal`
* `Lodging, except for congressperson from Distrito Federal`
* `Aircraft renting or charter of aircraft`
* `Watercraft renting or charter`
* `Automotive vehicle renting or charter`
* `Telecommunication`

**Comment by Irio** [comment]
👍 for the gender neutral pronoun.

Changed `txNomeParlamentar`, `ideCadastro`, `nuCarteiraParlamentar`, `sgUF` (to `state`), `txtTrecho` and all the subquota descriptions according to your suggestions, @cuducos. Did not change 2 of them:

* `txtNumero`: seem to refer to the attribute `indTipoDocumento`, "0, para Nota Fiscal; 1, para Recibo; e 2, para Despesa no Exterior". Maintained as `document_number` and `document_type`. Would you prefer another word for "documento" here?

> O conteúdo deste dado representa o número de face do documento fiscal emitido ou o número do documento que deu causa à despesa debitada na cota do deputado.

* `txtCNPJCPF`: I prefer not localize the ID names because this could cause confusion for both parties: those who know the Brazilian terms, and those trying to find more about Brazilian EINs. Also, if the payment was made for a person (e.g. real estate), the document used if CPF (SSN?).

---

Talking about optimizing the script, I wouldn't consider a high priority for now. Already generated the files and have them on S3; will be adding the links before merging this branch. If you can't optimize it, we would update the files weekly or monthly (adding the most recent receipts received).

If you want to work on it, that's surely welcome - giving for more people the chance of running the whole stack by themselves. I can say in advance that I've tried not using `xml_soup.find_all` (which allocates memory for all the XML nodes) but `xml_soup.select('DESPESA:nth-of-type(%s)' % index)` on every iteration; also failed for having no memory after thousands of records.

**Comment by cuducos** [comment]
Thanks for the explanation about `txtNumero`,  makes sense!

---

About the EIN you're right, its really for business only. Individuals have an Individual Taxpayer Identification Number (ITIN) — which is different from the SSN (let's say it's CNPJ ~ EIN, CPF ~ ITIN and PIS/PASEP ~ SSN). I'm fine with `cnpjcpf` or something like that, and I'd be fine with `ein_or_itin` or something like that too. It's up to you ; ) In this big mess it might make sense to go with the Brazilian terms… I'd just be more literal and do it as `cnpj_or_cpf` (I imagine it'd be easier from a _gringo_ to google for “cnpj or cpf” than “cnpjcpf” altogether).  But that's merely a tiny tiny detail.

---

>  will be adding the links before merging this branch

Yay! That's great.

I might try to optimize anyway just to have a _strategy_ if we stumble on similar issues in the future. My strategy is to write a slower script that depends mostly on file system, not memory. Slower, but will work without requiring 60GB of RAM (and some dollars). My first attempt will be to write bits of the large file in temp files (each bit in a different file), then remove the large file from memory, and then write the bits (one by one) into the CSV. Gonna create a branch based on this one and send you a PR later today, ok?

**Comment by cuducos** [comment]
@Irio What kind of issue you've had with `AnosAnteriores.xml`? Was a `OSError: [Errno 22] Invalid argument` on read? That might be a Mac OS X bug, but I have to investigate further…

**Comment by Irio** [comment]
@cuducos That's a known issue of Python 3 when opening files too large for
the available amount of RAM. Documented solutions are using Python 2 or
increasing the RAM available.

**Comment by cuducos** [comment]
Done in PR #8: longer and slower script, but worked in my 8Gb RAM computer for `AnosAnteriores.xml`.

**Comment by hyena22** [comment]
what do subquota (is it the task?), document value, remark value mean? Also what is the main quantity we are looking at, i.e. the money spent for each task?

**Comment by hyena22** [comment]
Also what is the granularity of the data? I assume each individual task. Am i correct?

**Comment by cuducos** [comment]
Following @hyena22's last post/comment, we might add to this PR a translation (en-US) of this [table](http://www2.camara.leg.br/transparencia/cota-para-exercicio-da-atividade-parlamentar/explicacoes-sobre-o-formato-dos-arquivos-xml) (the one saved for us on `data/datasets_format.html`). This translated version could clarify the translation for each variable and a English description for them. I'm just not sure about where to add this file… any ideas?

**Comment by cuducos** [comment]
And answering @hyena22's questions:

* `subquota` is the kind (type? category?) of expense a record refers to (transport, lodging etc.); take a look in `subquota_description` in [`develop/2016-08-08-im-translate-dataset.ipynb`](https://github.com/datasciencebr/serenata-de-oudamor/blob/ba028b332a98bd2cefcdeb6627db411df4bbf756/develop/2016-08-08-im-translate-dataset.ipynb);
* `document_value` is the main value of the expense a record refers to;
* `remark_value` I double checked the translation because I didn't even know the term in Portuguese (i.e. _glosa_); it _looks like_ that sometimes there could be a difference in the estimation of an expense and the actual cost, so a extra payment might be needed — actually we should confirm this with an expert (any ideas who'd know that? cc @Irio @cabral).

Ref. what is the main quantity we're are looking at, I think it depends. The main value itself is `document_value`, but I think we might triangulate that with more contextual data to have something meaningful.

**Comment by Irio** [comment]
@cuducos 

PT and EN versions of a Markdown file with a definition list or table with the contents of the `data/datasets_format.html` file (and not having it anymore) do the job of explaining. Will work on them and include in this branch.

On your question about `remark_value` and cost attributes, `vlrLiquido`/`net_value` seems to be value we want to spend more time analyzing, since it is the value the politician gets reimbursed[1]. Just contacted Lúcio Big (from http://ops.net.br/) asking him about these specific attributes.

[1]:
> O seu conteúdo representa o valor líquido do documento fiscal ou do documento que deu causa à despesa e será calculado pela diferença entre o Valor do Documento e o Valor da Glosa. É este valor que será debitado da cota do deputado. Caso o débito seja do Tipo Telefonia e o valor seja igual a zero, significa que a despesa foi franqueada.

**Comment by cuducos** [comment]
Many thanks, @irio! Awesome.

In our version of this table we could link/include Lúcio's remark on `remark` (yes, pun intended).

I can work on or help you with this table. Let me know if you wanna me to take over, or how to give you a hand ; )

**Comment by Irio** [comment]
@cuducos Would be a great help if you could create a script for generating these Markdowns from the html already in `data/`. This would give me time to wrap up the pull request with scripts for setting up contributors' environments with needed datasets, already translated and updated.

**Comment by cuducos** [comment]
Sure thing. I just added a Issue #9 for that ; )

**Comment by Irio** [comment]
Do you plan to merge your branch into this one? Otherwise I'm already satisfied with the current status and would ask for final review before merge. @cuducos

**Comment by cuducos** [comment]
My branch can be merged later, don't worry about it. I can't promise a code
review before Monday though…

**Pull request merged**
