### PR TITLE
Enterprises who received more

### PR DESCRIPTION
**Pull request by cabral**
Creating a list of the enterprises who receive more to help the field investigators.

### CODE REVIEW

**Comment by cuducos** [comment]
In a way @pmargreff has [already done it](http://64.137.188.230/#/empresas). @cabral do you need it in any specific format?

**Comment by cuducos** [comment]
Oops… sorry. I comment as it was an Issue, not a PR. My bad.

**Comment by cabral** [comment]
WIP 
Now have a very basic function to call every subquota and receive basic info

**Comment by cuducos** [comment]
Closed by inactivity

**Pull request closed without merging**
