### PR TITLE
feature: checking if the net_value pass the limit in subquota with limit defined

### PR DESCRIPTION
**Pull request by pmargreff**
Commit related with issue #135.

### CODE REVIEW

**Comment by pmargreff** [comment]
The values get over the limit aren't so high how I imagined, anyway I would know the procedure to demand the values back from the deputies? 

Another nice nuance i get in some moment, for the fuel spent have exactly the same value for a lot of people, it's almost impossible, so in a near future, I'll check the values to see if they came from the same source, and how it's distributed through the fuel companies. It's very suspicious.

**Comment by pmargreff** [comment]
Any reason for not accept that? Did you try the refund from these values?

**Comment by cuducos** [comment]
Hi @pmargreff — sorry about taking so long to get back, and thanks for the contribution (and the reminder).

I'd say that before merging that we have to address the issue about making Julia available in the repo setup, as @anaschwendler [mentioned the other day](https://github.com/datasciencebr/serenata-de-amor/issues/135#issuecomment-262855451).

**Comment by cuducos** [comment]
Closed by inactivity — but anyone wiling to bring Julia in is welcomed to re-open this and allow everyone to run Julia on notebooks easily ; )

**Pull request closed without merging**
