### PR TITLE
Add script to fetch congresspeople details

### PR DESCRIPTION
**Pull request by caiopo**
I talked to @joniarroba about useful data to create analysis that is available at Camara's API (e.g. age) but isn't fetched by the scripts in `src/`.

So this PR adds a new script that fetches and creates a `pandas.DataFrame` with `birth_date`, `civil_name`, `congressperson_id`, `gender`.

This script is "forked" from `src/fetch_civil_names.py`, but uses Camara's API (as noted on #224).

### CODE REVIEW

**Comment by cuducos** [comment]
IMHO contributions in that sense should enhance or completely replace `src/fetch_civil_names.py` — and not add another script that generates (partially) duplicated data. Also we need to document this script in `CONTRIBUTING.md`.

TBH with this PR I believe we don't need `src/fetch_civil_names.py` anymore.

So what I suggest is: 

- [ ] Document this new script in `CONTRIBUTING.md`
- [ ] Mark `src/fetch_civil_names.py` as _deprecated_ in `CONTRIBUTING.md`
- [ ] Generate a dataset and share the link with us so we can add to the `serenata_toolbox` list of datasets (the list that is downloaded in the `setup` process)

What do you think about it?

**Comment by caiopo** [comment]
>  Document this new script in CONTRIBUTING.md
> Mark src/fetch_civil_names.py as deprecated in CONTRIBUTING.md

Done (9b2331a)

>  Generate a dataset and share the link with us so we can add to the serenata_toolbox list of datasets (the list that is downloaded in the setup process)

https://we.tl/yrnPxCmQFA

The next step is probably refactoring anything that depends on `src/fetch_civil_names.py` to use `src/fetch_congressperson_details.py`, right?

**Comment by jtemporal** [comment]
> The next step is probably refactoring anything that depends on src/fetch_civil_names.py to use src/fetch_congressperson_details.py, right?

That's about right, AFAIK there isn't anything depending on it... But if there is, yes, a refactor is in order.

**Comment by cuducos** [comment]
I'm sorry @caiopo — it took a while for me to get back to this PR and the WeTransfer link is not working anymore. Can you re-upload it?

Besides that, do you confirm no refactor is needed as in:

> The next step is probably refactoring anything that depends on `src/fetch_civil_names.py` to use `src/fetch_congressperson_details.py`, right?

Next I think this is good to merge ; ) Many  many thanks

**Comment by caiopo** [comment]
Hi! :smile: 

According to a `grep -ri "civil-names" develop/` (searches for `civil-names` in files inside `develop/`), no files depend on that dataset, so I deleted it on d7aaa824f133e89f0eee5c0d81a4bc2d1709bc71.

Here's the new WeTransfer link: https://we.tl/9WAO5WVpUW

I also fixed the conflicts so the branches can be automatically merged. :)

**Comment by cuducos** [comment]
Many thanks, @caiopo 🎉

**Pull request merged**
