### PR TITLE
Jupyter Notebook not available (docker) #274

### PR DESCRIPTION
**Pull request by arioston**
Hi,
I had made a change on CONTRIBUTING.md, because --rm don't expose the ports.

### CODE REVIEW

**Comment by anaschwendler** [comment]
Hi @arioston, thanks for the contribuition!

What I did to test this PR:

1. Clone the project:
```console
$ git clone git@github.com:datasciencebr/serenata-de-amor.git
```

2. Change to serenata's folder:
```console
$ cd serenata-de-amor 
```

3. Change to @silviodc's branch:
```console
$ git checkout -b arioston-master master
$ git pull https://github.com/arioston/serenata-de-amor.git master
```

4. The steps to run the project:
```console
$ cp config.ini.example config.ini
$ docker-compose build
$ docker-compose up -d
$ docker-compose run --service-ports research jupyter notebook
```

5. Test if it works, and it work fine, thanks @arioston!

image


Merging it!

**Comment by cuducos** [comment]
Hi. I would like to re-open this discussion: here only `docker-compose up -d` works and I can access `localhost:8888` **without** `docker-compose run --service-ports research jupyter notebook`.

As `docker-compose up -d` doesn't take the argument `--rm` I really couldn't get OP's description:

> I had made a change on CONTRIBUTING.md, because --rm don't expose the ports.

Can you clarify this issue @arioston and @anaschwendler so we can clarify our documentation?

**Comment by arioston** [comment]
Hi,

If you wanna run only the command to start jupyter notebook on the research service then :
- docker-compose run --service-ports research jupyter notebook
- if you don't use the [--service-ports](https://docs.docker.com/compose/reference/run/) , the port will not be exposed because by default they are not.

> As docker-compose up -d doesn't take the argument --rm I really couldn't get OP's description:
> > I had made a change on CONTRIBUTING.md, because --rm don't expose the ports.

the docker-composer  up doesn't take, but docker-composer run takes. The command --rm will remove container after the run.

**Comment by arioston** [comment]
I had tried to access the jupyter without step 4, @cuducos  was right the notebook is already exposed, step 4 only is needed if the container is down and I wanna to start only the research container.

**Comment by cuducos** [comment]
Many thanks for the clarification, @arioston — better fixed in #294 now IMHO

**Pull request merged**
