### PR TITLE
[WIP] Add src/fetch_deputies_advisors.py

### PR DESCRIPTION
**Pull request by bruno-schmidt**
This tool tries to solve issue #139 

The development of this script started in a repository on my account ([here](https://github.com/bruno-schmidt/sda-dep-advisors))

Still a working in progress!

### CODE REVIEW

**Comment by Irio** [comment]
What's missing here, @bruno-schmidt? Are you still working on it?

**Comment by bruno-schmidt** [comment]
@Irio Hello! I was waiting for a code review only. We were talking in #139 but it's functional. Limited to the current deputies only!

**Comment by cuducos** [comment]
@bruno-schmidt while reviewing your script I started to do some minor edits and tests and I ended up sending you a PR with some suggestions. Let me know how you find it, ok?

**Comment by bruno-schmidt** [comment]
@cuducos that's nice! I have a lot to learn from your changes :smile: I just accepted your PR!

**Comment by cuducos** [comment]
Hell yeah, @bruno-schmidt — don't hesitate to get in touch in PVT if you have any doubts about the code.

Bruno, would you mind documenting this script in the proper section in our `CONTRIBUTING.md`?

@Irio Python-wise this script is really good. Data science-wise I'd raise two things to you since for me it's already GTM: maybe you would like to check the data output (some [snippet here](https://github.com/bruno-schmidt/serenata-de-amor/pull/1#issue-196145479)), and the script is only able to scrap data from current congresspeople (not from former) — anyway, this is not a problem _per se_, I guess…

**Comment by jtemporal** [comment]
@bruno-schmidt great work! 🎉

@cuducos LGTM!

Minor considerations:
 - would change where is written deputy/deputies for congresspeople/person

But that is totally 💅... Would merge it.

**Comment by jtemporal** [comment]
I'm merging this one and opening up a issue so we can generate the advisors data and take care of the 💅 part ;)

**Pull request merged**
