### PR TITLE
Update docker image and fix issues with conda packages installation

### PR DESCRIPTION
**Pull request by fgrehm**
Not sure if this is going to break things for people running the env outside of Docker but this is what I've done to get up and running again after reformating my laptop.

Tks to @cabral for the tip on using the `bioconda` channel.

BTW, things look a lot nicer on this new jupyter release 😍 

screen shot 2017-05-19 at 10 59 34

/cc @cuducos

### CODE REVIEW

**Comment by jtemporal** [comment]
I doesn't look likely to break anything for people that do not use Docker... I'll test it out later today to be sure ;)

>BTW, things look a lot nicer on this new jupyter release 😍

It really does look nicer, doesn't it?! It is a shame that GitHub do not render the tables like that though ¯\\\_(ツ)_/¯

**Comment by cuducos** [comment]
As I comment to @cabral last week I think a more stable fix would be to to install `grequest` from `pip`, not from `conda` (after all it has nothing to do — directly — with data science, so `pip` migh handle it better). That way we don't depend on `bioconda` (we can remove that). Do you mind addressing it too in this PR?

**Comment by cuducos** [comment]
LGTM. @jtemporal I saw you struggling with `gresquests` in #244 — any thoughts here? I'll let for you to merge, ok?

**Comment by jtemporal** [comment]
>@jtemporal I saw you struggling with gresquests in #244 — any thoughts here? 

@cuducos Yes I was, but @rougeth came up with a nice way to solve the problem I was having =)

So merging this one =)

**Pull request merged**
