### PR TITLE
Benford analysis on net_values

### PR DESCRIPTION
**Pull request by pingfreud**
Script with basic Benford analysis on the net_values using R.

I'm having trouble to run the R kernel inside Jupyter Notebook. I'll try to work on it in the next few days, but in the meantime, this PR has the initial script.

### CODE REVIEW

**Comment by Irio** [comment]
Great idea for analysis, @pingfreud. Contact me in private if you want help with your environment. Better solve this issue with you and document so new contributors don't have it again.

**Comment by pingfreud** [comment]
Hello @Irio ,

Thanks for the help with Jupyter and R kernel.

**Comment by Irio** [comment]
All of this look very good, @pingfreud. Going to ask you a few things to be changed before merging your analysis:

- [ ] Rename your notebook to contain your GitHub username (`2016-09-20-im-benford-analysis` becomes `2016-09-20-pingfreud-benford-analysis`.
- [ ] Export the notebook to `.py` and `.html`. This will make them easier to be read in GitHub. Highly recommended to autogenerate on every file save, following config change at https://github.com/datasciencebr/serenata-de-amor/blob/59687a7a087f3326538979fef30306c8c2083e99/CONTRIBUTING.md#best-practices
- [ ] Move `benford.subquota.R` to `src` folder. It's the intended place for auxiliary scripts, making them easily accessible for future contributors.
- [ ] I feel `benford.R` would be better if directly put in the notebook cell, since is not generic enough to be reused in other analysis. Thoughts against doing so?
- [ ] About your conclusions and formatting the output to Serenata's Machine Learning model, could you output the whole DataFrame at the end of the notebook and conclude with a few words why you think these results can be useful for our domain? I have ideas, but would be better to have them documented for everyone.

In general, excellent analysis with good documentation and background research. Hope we can merge it soon.

**Comment by cuducos** [comment]
Close by inactivity. But anyone – specially @jtemporal who loves R and, now, Benford's Law — is free to jump in and take this awesome contribution further.

**Pull request closed without merging**
