### PR TITLE
Issue #295 - New descriptive analysis

### PR DESCRIPTION
**Pull request by mathcunha**
The info to answer the questions can be found at 2017-07-04-reimbursements.xz. 

But, to answer Question 2, I had to collect quota information available at http://www2.camara.leg.br/comunicacao/assessoria-de-imprensa/cota-parlamentar.

To complete the quota information, I used the same approach presented at 2017-05-01-luipillmann-intro-to-reimbursements.ipynb

### CODE REVIEW

**Comment by cuducos** [comment]
Hi @mathcunha — many many thanks! That's a really good work!

Before merging I think we could improve the notebook in some ways.

First of all I'm sorry I haven't replied to your doubt in #295 just in time. But I'm happy you could find the links with the total amount allowed by CEAP by yourself.

* Charts are really useful and great overall. But as the purpose of this analysis is to gather numbers to _use as argument when standing for better control and transparency of CEAP expenses_ having the final values at hand is also important. Is it possible to plot charts **and** table with the full values? Alternatively if you can find a way to plot the number each chart bar correspond to, that would be enough.
* Charts from states with a great number of deputies are a bit tight, can you expand it a bit so it's easier to read congresspeople names (and eventually values plotted next to the bars)?
* I see you've left some commented code (e.g. cells 9, 14 and 15) but I couldn't get why. Would you mind cleaning up **or** if you're leaving it as examples, you can describe in a text cell what these examples are about and actually run the code to illustrate.

What do you think?

Once more, thank you for the contribution ; )

**Comment by mathcunha** [comment]
Hi @cuducos ,

No problem! ;)

I found a way to plot the labels for each bar and implemented two functions to plot the data:

1. _plot_data_diff_axis_ - plots one figure per state. So, at the end, you will have 27 figures. This charts provides a focus on the states values once the y axis range enclosures just the state values;
2. _plot_data_same_axis_ - plots one only figure. The states share the same y axis and sizes. This can be a problem because some states have great number of deputies.

This two functions allow the user to pick a chart that better suits your needs.

Thank you for the ideias!

**Comment by cuducos** [comment]
Hi @mathcunha — once more thank you very much for the contribution!

Claudia and I were looking at the notebook and there's some data that is really difficult to get meaning from them. 

First of all we believe that having a table per month will offer us a clearer picture of the expenses: if a someone, for example, was in office for a few months, his average diluted in the term will be very slow (eg compare you charts to data found on [this website](http://www.deepask.com/goes?page=edinho-montemor-Acompanhe-o-gasto-do-deputado-federal-com-aluguel-de-carro))

This would change the output format of the next two sections: ratio when compared to the total available and the expenses by subquota (again a month by month table would be helpful: for example, expenses during vacation and official breaks should be lower than other months)

I'm sorry we weren't able to foreseen that. Are you willing to work on that? If not I do comprehend and I'm glad anyway ; )

**Comment by cuducos** [comment]
For example:


# SP

| Congressperson | 01/2015 | 02/2015 | 03/2015 | … |
|------------|-----|-----|-----|-----|
| Fulano | 20.342 | 21.543 | 21.635 | … |
| Ciclano | 20.342 | 21.543 | 21.635 | … |

**Comment by mathcunha** [comment]
Hi ,

I understand the difficulties to see the information that you need plotting just the overall average. But the issue don't clearly asks for this vision by month_year.

This new version displays the data using tables. You will see lots of NaN where there is nothing to be displayed.

Remember you can filter the data In#10 has an example.

**Comment by cuducos** [comment]
> I understand the difficulties to see the information that you need plotting just the overall average. But the issue don't clearly asks for this vision by month_year.

Actually the charts you plot raised our attention to subtle circumstances in which the overall averages made no sense at all. So, yeas, the charts were very useful in that sense.

>  You will see lots of NaN where there is nothing to be displayed.

Is there any chance this _lots of `NaN`_ were skewing the overall averages before?

Again I'm sorry I couldn't brief the notebook properly. Sometimes seeing the visualization is the best way to improve it. I think the month-by-month view is more informative as `sum`, not `mean` (cell 15).

Again I'll ask: Are you willing to work on that? If not I do comprehend and I'm glad anyway — I might take over from now, keeping your commit history so you'll get credit when this is merged ; )

**Comment by mathcunha** [comment]
Hi,
> Is there any chance this lots of NaN were skewing the overall averages before?

This _NaN_ are generated when I convert the year+month to columns and the congressperson has no reimbursement for the given period (month+year). Which does not affect the aggregations.

> Again I'll ask: Are you willing to work on that? If not I do comprehend and I'm glad anyway — I might take over from now, keeping your commit history so you'll get credit when this is merged ; )

If you can take over, please be my guest ;) And, if you need any assistance I will be glad to help.

**Comment by cuducos** [comment]
We've taken a different strategy for #295, so I'll accept this notebook as it is : )

(About #295 we gave a couple of volunteers working on demand to this data for such arguments.)

**Pull request merged**
