### PR TITLE
Add lodging expense analysis based on simple mean/std comparisons

### PR DESCRIPTION
**Pull request by samuelgrigolato**
This should be considered as an initial approach to #26. One may argue that there isn't any official data being scraped and considered yet, but this mean/std approach may prove to be useful for further analysis, with or without external data.

### CODE REVIEW

**Comment by cuducos** [comment]
Hi @samuelgrigolato! Very interesting analysis, many thanks for that.

Would you mind adding the `.html` and `.py` versions (as [explained here](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#best-practices)) so I can consider this PR good to merge?

**Comment by samuelgrigolato** [comment]
Done!

Am I right to assume that the .py/.html versions should be versioned *in addition to* and not *in replacement of* the ipynb file?

Also note that I amended my last commit, effectively dropping the current one, in order to keep this PR with a clean history. Please tell me if the current commit is already merged somewhere so I can revert this move and avoid trouble =).

I'd also like to ask how can I be _assigned_ something else to do? I'm looking forward to help both in web scraping and data analysis. I know there are the issues page, but maybe you can provide some pointers on specific areas that would appreciate some work?

**Comment by anaschwendler** [comment]
Hi @samuelgrigolato!

First of all, thanks for your contribuition, very well done, you explained the idea very well!
The only thing I would like to add is that you can adapt your analysis to the new dataset based on reimbursements, you can read about here:  #143

About your question, we have a roadmap that is guiding us for this time, there are many issues that focus on data scraping and analysis like nepotism, meal outliers, there is something that you're interested about it? That would help to us to find something for you :)

**Comment by cuducos** [comment]
Just complementing what @anaschwendler just said: here are briefly [our roadmap](https://github.com/datasciencebr/serenata-de-amor/milestones) for the next weeks — each roadmap has some issues and PRs related to it. Beyond that feel free to reach us on the [Telegram group](http://bit.ly/2cUBFr6) if we can help you help us ; )

**Comment by samuelgrigolato** [comment]
@anaschwendler @cuducos  I just pushed a new version of my analysis. Now it consumes the new reimbursements dataset. I hope I got correctly the meaning of the added columns, though. Please let me know if `total_net_values` was not the intended direct replacement for the old `net_value` so I can fix it. :smile:

I'm also taking a look at the roadmaps. As soon as I feel inclined to spend some brain tissue into something (that won't be too hard, I guess) I'll let you know at the comments.

**Comment by anaschwendler** [comment]
Hi @samuelgrigolato!
Yes, that's right we are using `total_net_value` to replace the old `net_value`, so that's fine.

Please let us know, if you need something, or are having some doubts, call me or @cuducos  on telegram :)
We are there to explain everything about the project!
By now, thanks for you contribuition, I'll take a better look into it, and if I didn't find anything new, I will merge it to the project.

**Comment by anaschwendler** [comment]
Hi @samuelgrigolato i was taking a last closer look to your notebook, and its good to merge!

The last thing we need from you is change the name of the notebooks, sorry for not noticing that before, but now we are using the github username at it, do it if whenever you can, and then i'll merge it.

Really liked your conclusion and your research in a way to find suspicious reimbursements :)

**Comment by samuelgrigolato** [comment]
Hello @anaschwendler!

I'm glad you like the analysis, thank you!

Regarding the new naming rules, there's no problem at all, I've pushed a new commit following your orientation. Please let me know if you happen to find anything else I need to fix.

I opted not to amend my commit this time, maybe it is helpful for the history to have this kind of action explicity logged. If you think otherwise, feel free to correct me.

**Comment by anaschwendler** [comment]
That's fine, thanks for the last commit :)
I'll be merging it right now.

Any doubts send us a message on telegram \o\
We're here to help!

**Pull request merged**
